/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookTrading.seller;

import jade.gui.TimeChooser;
import java.util.*;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author Ulis
 */
public class BookSellerGuiImpl extends javax.swing.JFrame implements BookSellerGui {
    private BookSellerAgent myAgent;
    
    private Date tglAwalPeminjaman;
    private Date tglAkhirPeminjaman;
    private Set<String> daftarPeminjaman;
    private Set<String> daftar; //menyimpan hasil setelah status diubah
    
    /**
     * Creates new form BookSellerGuiImpl
     */
    public BookSellerGuiImpl() {
        initComponents();
        this.logTA.setEnabled(false);
        this.daftarPeminjaman = new HashSet<String>();
        this.daftar = new HashSet<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        NamaPelanggan = new javax.swing.JLabel();
        NamaPelanggan1 = new javax.swing.JLabel();
        judulNovelMajalah = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        HargaPerHari = new javax.swing.JLabel();
        awalPeminjaman = new javax.swing.JLabel();
        awalPeminjaman1 = new javax.swing.JLabel();
        awalPeminjaman3 = new javax.swing.JLabel();
        AddPeminjaman = new javax.swing.JButton();
        isiJudul = new javax.swing.JTextField();
        isiHargaPerHari = new javax.swing.JTextField();
        isiNamaPelanggan = new javax.swing.JTextField();
        isiAlamat = new javax.swing.JTextField();
        isiAwalPeminjaman = new javax.swing.JTextField();
        isiAkhirPeminjaman = new javax.swing.JTextField();
        ubahStatusPesanan = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTA = new javax.swing.JTextArea();
        SetAwalPeminjaman = new javax.swing.JButton();
        SetAkhirPeminjaman = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        cariNama = new javax.swing.JTextField();
        UbahStatus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamaPelanggan.setText("Pelanggan");

        judulNovelMajalah.setText("Judul Novel/Majalah");

        alamat.setText("Alamat");

        HargaPerHari.setText("Harga/Hari");

        awalPeminjaman.setText("Awal Peminjaman");

        awalPeminjaman1.setText("Akhir Peminjaman");

        awalPeminjaman3.setText("Ubah Status");

        AddPeminjaman.setText("Add");
        AddPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPeminjamanActionPerformed(evt);
            }
        });

        isiJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiJudulActionPerformed(evt);
            }
        });

        isiAkhirPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiAkhirPeminjamanActionPerformed(evt);
            }
        });

        ubahStatusPesanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diproses", "Di kirim ke pelanggan", "Di pelanggan", "Selesai" }));
        ubahStatusPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahStatusPesananActionPerformed(evt);
            }
        });

        jLabel1.setText("Daftar Peminjaman");

        logTA.setColumns(20);
        logTA.setRows(5);
        jScrollPane1.setViewportView(logTA);

        SetAwalPeminjaman.setText("Set");
        SetAwalPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetAwalPeminjamanActionPerformed(evt);
            }
        });

        SetAkhirPeminjaman.setText("Set");
        SetAkhirPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetAkhirPeminjamanActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        UbahStatus.setText("Ubah");
        UbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahStatusActionPerformed(evt);
            }
        });

        jLabel2.setText("Masukkan Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(NamaPelanggan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaPelanggan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(judulNovelMajalah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HargaPerHari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isiNamaPelanggan)
                            .addComponent(isiHargaPerHari)
                            .addComponent(isiJudul))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(awalPeminjaman1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alamat)
                                .addComponent(awalPeminjaman)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isiAwalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SetAwalPeminjaman))
                            .addComponent(isiAlamat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isiAkhirPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SetAkhirPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cariNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubahStatusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(UbahStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(awalPeminjaman3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaPelanggan1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulNovelMajalah)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamat)
                            .addComponent(isiAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiHargaPerHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaPerHari)
                            .addComponent(awalPeminjaman)
                            .addComponent(isiAwalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SetAwalPeminjaman))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(awalPeminjaman1)
                            .addComponent(isiAkhirPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SetAkhirPeminjaman)
                            .addComponent(isiNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaPelanggan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(awalPeminjaman3)
                    .addComponent(ubahStatusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbahStatus)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPeminjamanActionPerformed
        // TODO add your handling code here:
        int hargaPerHari = Integer.parseInt(this.isiHargaPerHari.getText());
        long diff = this.tglAkhirPeminjaman.getTime() - this.tglAwalPeminjaman.getTime();
        long jumlahHari = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);;
        int totalHarga = (int) (hargaPerHari*jumlahHari);
        
        this.notifyUser(this.isiJudul.getText()+","+hargaPerHari+","+totalHarga+","+this.isiNamaPelanggan.getText()+","+this.isiAlamat.getText()+","+
                this.tglAwalPeminjaman+","+this.tglAkhirPeminjaman+","+"Di proses");
        this.daftarPeminjaman.add(this.isiJudul.getText()+","+hargaPerHari+","+totalHarga+","+this.isiNamaPelanggan.getText()+","+this.isiAlamat.getText()+","+
                this.tglAwalPeminjaman+","+this.tglAkhirPeminjaman+","+"Di proses");
        
    }//GEN-LAST:event_AddPeminjamanActionPerformed

    private void isiJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiJudulActionPerformed

    private void isiAkhirPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiAkhirPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiAkhirPeminjamanActionPerformed

    private void ubahStatusPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahStatusPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahStatusPesananActionPerformed

    private void SetAwalPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetAwalPeminjamanActionPerformed
        // TODO add your handling code here:
        Date d = this.tglAwalPeminjaman;
        if (d == null) {
            d = new Date();
        }

        TimeChooser tc = new TimeChooser(d);
        if (tc.showEditTimeDlg(BookSellerGuiImpl.this) == TimeChooser.OK) {
            this.tglAwalPeminjaman = tc.getDate();
            this.isiAwalPeminjaman.setText(this.tglAwalPeminjaman.toString());
        }
    }//GEN-LAST:event_SetAwalPeminjamanActionPerformed

    private void SetAkhirPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetAkhirPeminjamanActionPerformed
        // TODO add your handling code here:
        Date d = this.tglAkhirPeminjaman;
        if (d == null) {
            d = new Date();
        }

        TimeChooser tc = new TimeChooser(d);
        if (tc.showEditTimeDlg(BookSellerGuiImpl.this) == TimeChooser.OK) {
            this.tglAkhirPeminjaman = tc.getDate();
            this.isiAkhirPeminjaman.setText(this.tglAkhirPeminjaman.toString());
        }
    }//GEN-LAST:event_SetAkhirPeminjamanActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.isiJudul.setText("");
        this.isiHargaPerHari.setText("");
        this.isiAwalPeminjaman.setText("");
        this.isiAkhirPeminjaman.setText("");
        this.isiAlamat.setText("");
        this.isiNamaPelanggan.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        myAgent.doDelete();
    }//GEN-LAST:event_ExitActionPerformed

    private void UbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahStatusActionPerformed
        // TODO add your handling code here:
        //this.isiStatus.setText((String) this.ubahStatusPesanan.getSelectedItem()); 
        String nama = this.cariNama.getText();
        // Converting HashSet to Array
        String[] arrSet = this.daftarPeminjaman.toArray(new String[this.daftarPeminjaman.size()]);
        String hasil = "";
        for(int i=0;i<arrSet.length;i++){
            String[] hasilSplit = arrSet[i].split(",",9);
            if(nama.equals(hasilSplit[3])){
               hasilSplit[7] = (String) this.ubahStatusPesanan.getSelectedItem(); 
                for(int j=0;j<hasilSplit.length;j++){
                    hasil+=hasilSplit[j]+",";
                }
            }
            else{
                for(int j=0;j<hasilSplit.length;j++){
                    hasil+=hasilSplit[j]+",";
                }
            }
            this.daftar.add(hasil);
        }   
        this.logTA.setText("");
        String[] arrSet1 = this.daftar.toArray(new String[this.daftar.size()]);
        for(int k=0;k<arrSet1.length;k++){
            this.notifyUser(arrSet1[k]);
        }   
    }//GEN-LAST:event_UbahStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSellerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSellerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSellerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSellerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
                new BookSellerGuiImpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPeminjaman;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel HargaPerHari;
    private javax.swing.JLabel NamaPelanggan;
    private javax.swing.JLabel NamaPelanggan1;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SetAkhirPeminjaman;
    private javax.swing.JButton SetAwalPeminjaman;
    private javax.swing.JButton UbahStatus;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel awalPeminjaman;
    private javax.swing.JLabel awalPeminjaman1;
    private javax.swing.JLabel awalPeminjaman3;
    private javax.swing.JTextField cariNama;
    private javax.swing.JTextField isiAkhirPeminjaman;
    private javax.swing.JTextField isiAlamat;
    private javax.swing.JTextField isiAwalPeminjaman;
    private javax.swing.JTextField isiHargaPerHari;
    private javax.swing.JTextField isiJudul;
    private javax.swing.JTextField isiNamaPelanggan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulNovelMajalah;
    private javax.swing.JTextArea logTA;
    private javax.swing.JComboBox ubahStatusPesanan;
    // End of variables declaration//GEN-END:variables

    public void setAgent(BookSellerAgent a) {
        myAgent = a;
        setTitle(myAgent.getName());
    }

    @Override
    public void notifyUser(String message) {
        logTA.append(message+"\n");
    }
}
