/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookTrading.StockManager;

import bookTrading.seller.BookSellerAgent;
import bookTrading.seller.BookSellerGui;
import java.util.*;

/**
 *
 * @author Ulis
 */
public class StockManagerGuiImpl extends javax.swing.JFrame implements StockManagerGui {
    private StockManagerAgent myAgent;
    private Set<String> daftarBuku;
    private Set<String> daftar; //menyimpan hasil setelah jumlah stock diubah
    /**
     * Creates new form StockManegerGuiImpl
     */
    public StockManagerGuiImpl() {
        initComponents();
        this.LogTextArea.setEnabled(false);
        this.daftarBuku = new HashSet<String>();
        this.daftar = new HashSet<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isiJudulBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        isiPenulisBuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        isiKetersediaan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        isiHargaPerHari = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LogTextArea = new javax.swing.JTextArea();
        isiJenisBuku = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        judulBukuUpdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ketersediaanUpdate = new javax.swing.JTextField();
        AddBuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Judul Buku");

        jLabel2.setText("Penulis Buku");

        isiPenulisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiPenulisBukuActionPerformed(evt);
            }
        });

        jLabel3.setText("Ketersediaan");

        jLabel4.setText("Harga/Hari");

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        LogTextArea.setColumns(20);
        LogTextArea.setRows(5);
        jScrollPane1.setViewportView(LogTextArea);

        isiJenisBuku.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novel", "Majalah" }));

        jLabel5.setText("Jenis Buku");

        jLabel6.setText("Judul Buku");

        jLabel7.setText("Ketersediaan");

        AddBuku.setText("Add");
        AddBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isiJenisBuku, 0, 176, Short.MAX_VALUE)
                            .addComponent(isiJudulBuku)
                            .addComponent(isiPenulisBuku)
                            .addComponent(isiKetersediaan)
                            .addComponent(isiHargaPerHari)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(judulBukuUpdate)
                                .addComponent(jLabel7)
                                .addComponent(ketersediaanUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(Update)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isiJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(isiPenulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiJenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isiKetersediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isiHargaPerHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judulBukuUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ketersediaanUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Update)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBuku)
                    .addComponent(Reset)
                    .addComponent(Exit))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiPenulisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiPenulisBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiPenulisBukuActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        this.LogTextArea.setText(" ");
        String judul = this.judulBukuUpdate.getText();
        String ketersediaan = this.ketersediaanUpdate.getText();
        // Converting HashSet to Array
        String[] arrSet = this.daftarBuku.toArray(new String[this.daftarBuku.size()]);
        String hasil = "";
        for(int i=0;i<arrSet.length;i++){
            String[] hasilSplit = arrSet[i].split(",",6);
            if(judul.equals(hasilSplit[0])){
                hasilSplit[3] = ketersediaan;  
                for(int j=0;j<hasilSplit.length;j++){
                    hasil+=hasilSplit[j]+", ";
                }
            }
            else{
                for(int j=0;j<hasilSplit.length;j++){
                    hasil+=hasilSplit[j]+", ";
                }
            }
            this.daftar.add(hasil);
            hasil = "";
        }     
        
        String[] arrSet1 = this.daftar.toArray(new String[this.daftar.size()]);
        for(int k=0;k<arrSet1.length;k++){
            this.notifyUser(arrSet1[k]+"\n");
        }       
    }//GEN-LAST:event_UpdateActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.isiJudulBuku.setText("");
        this.isiPenulisBuku.setText("");
        this.isiKetersediaan.setText("");
        this.isiHargaPerHari.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        myAgent.doDelete();
    }//GEN-LAST:event_ExitActionPerformed

    private void AddBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBukuActionPerformed
        // TODO add your handling code here:
        String jenisBuku = (String) this.isiJenisBuku.getSelectedItem();
        this.notifyUser("Tambah Buku : "+this.isiJudulBuku.getText()+","+this.isiPenulisBuku.getText()+","+jenisBuku+","+this.isiKetersediaan.getText()+","+
                this.isiHargaPerHari.getText());
        this.daftarBuku.add(this.isiJudulBuku.getText()+","+this.isiPenulisBuku.getText()+","+jenisBuku+","+this.isiKetersediaan.getText()+","+
                this.isiHargaPerHari.getText()); 
    }//GEN-LAST:event_AddBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagerGuiImpl().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBuku;
    private javax.swing.JButton Exit;
    private javax.swing.JTextArea LogTextArea;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JTextField isiHargaPerHari;
    private javax.swing.JComboBox isiJenisBuku;
    private javax.swing.JTextField isiJudulBuku;
    private javax.swing.JTextField isiKetersediaan;
    private javax.swing.JTextField isiPenulisBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulBukuUpdate;
    private javax.swing.JTextField ketersediaanUpdate;
    // End of variables declaration//GEN-END:variables

    public void setAgent(StockManagerAgent a) {
        this.myAgent = a;
        setTitle(myAgent.getName());
    }

    @Override
    public void notifyUser(String message) {
        this.LogTextArea.append(message+"\n");
    }
}
