/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pedro
 */
package bookTrading.borrower;

import bookTrading.seller.BookSellerGuiImpl;
import jade.gui.TimeChooser;
import java.awt.*;
import java.awt.Event.*;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.*;
import javax.swing.border.*;


public class BookBorrowerGuiImpl extends JFrame implements BookBorrowerGui {
    private BookBorrowerAgent myAgent;
    
    private Date tglAwalPeminjaman;
    private Date tglAkhirPeminjaman;

    /**
     * Creates new form BookBorrowerGuiImpl
     */
    public BookBorrowerGuiImpl() {
        initComponents();
        this.TextAreaLogs.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNovelMajalah = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        TextFieldTanggalAwal = new javax.swing.JTextField();
        ButtonKeluar = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        LabelNamaPeminjam = new javax.swing.JLabel();
        TextFieldTanggalAkhir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaLogs = new javax.swing.JTextArea();
        ComboBoxNovelMajalah = new javax.swing.JComboBox<String>();
        LabelAwalPeminjaman = new javax.swing.JLabel();
        LabelAkhirPeminjaman = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldAlamat = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();
        ButtonSetTanggalAwal = new javax.swing.JButton();
        ButtonSetTanggalAkhir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNovelMajalah.setText("Judul Novel/Majalah");

        LabelAlamat.setText("Alamat Pengantaran");

        ButtonKeluar.setText("Keluar");
        ButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKeluarActionPerformed(evt);
            }
        });

        ButtonTambah.setText("Tambah Pesanan");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        LabelNamaPeminjam.setText("Nama Peminjam");

        TextFieldTanggalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTanggalAkhirActionPerformed(evt);
            }
        });

        TextAreaLogs.setColumns(20);
        TextAreaLogs.setRows(5);
        jScrollPane1.setViewportView(TextAreaLogs);

        ComboBoxNovelMajalah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Philosopher's Stone/3000", "A Passage to India/2000", "Things Fall Apart/2000", "This Old House/4000", "Traditional Home/1000" }));
        ComboBoxNovelMajalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNovelMajalahActionPerformed(evt);
            }
        });

        LabelAwalPeminjaman.setText("Awal Peminjaman");

        LabelAkhirPeminjaman.setText("Akhir Peminjaman");

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        ButtonSetTanggalAwal.setText("Set Tanggal");
        ButtonSetTanggalAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSetTanggalAwalActionPerformed(evt);
            }
        });

        ButtonSetTanggalAkhir.setText("Set Tanggal");
        ButtonSetTanggalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSetTanggalAkhirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonKeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAwalPeminjaman)
                            .addComponent(LabelAkhirPeminjaman))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldTanggalAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(TextFieldTanggalAkhir))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonSetTanggalAwal)
                            .addComponent(ButtonSetTanggalAkhir)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(TextFieldAlamat))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelNamaPeminjam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelNovelMajalah)
                                    .addGap(31, 31, 31))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LabelAlamat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(ComboBoxNovelMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNovelMajalah)
                    .addComponent(ComboBoxNovelMajalah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNamaPeminjam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAwalPeminjaman)
                    .addComponent(ButtonSetTanggalAwal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAkhirPeminjaman)
                    .addComponent(ButtonSetTanggalAkhir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonKeluar)
                    .addComponent(ButtonTambah)
                    .addComponent(ButtonReset))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        String namaHarga = (String) this.ComboBoxNovelMajalah.getSelectedItem();
        String[] hasilSplit = namaHarga.split("/",2);
        int hargaPerHari = Integer.parseInt(hasilSplit[1]); //mengambil harga novel/
        long diff = this.tglAkhirPeminjaman.getTime() - this.tglAwalPeminjaman.getTime();
        long jumlahHari = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);;
        int totalHarga = (int) (hargaPerHari*jumlahHari);  
        
        this.notifyUser(hasilSplit[0]+","+hargaPerHari+","+totalHarga+","+this.TextFieldAlamat.getText()+","+
                this.tglAwalPeminjaman+","+this.tglAkhirPeminjaman+","+"Di proses");
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void TextFieldTanggalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTanggalAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTanggalAkhirActionPerformed

    private void ButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKeluarActionPerformed
        // TODO add your handling code here:
        myAgent.doDelete();
    }//GEN-LAST:event_ButtonKeluarActionPerformed

    private void ComboBoxNovelMajalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNovelMajalahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNovelMajalahActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        this.TextFieldNama.setText("");
        this.TextFieldAlamat.setText("");
        this.TextFieldTanggalAwal.setText("");
        this.TextFieldTanggalAkhir.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void ButtonSetTanggalAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSetTanggalAwalActionPerformed
        // TODO add your handling code here:
        Date d = this.tglAwalPeminjaman;
        if (d == null) {
            d = new Date();
        }

        TimeChooser tc = new TimeChooser(d);
        if(tc.showEditTimeDlg(BookBorrowerGuiImpl.this) == TimeChooser.OK) {
            this.tglAwalPeminjaman = tc.getDate();
            this.TextFieldTanggalAwal.setText(this.tglAwalPeminjaman.toString());
        }
    }//GEN-LAST:event_ButtonSetTanggalAwalActionPerformed

    private void ButtonSetTanggalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSetTanggalAkhirActionPerformed
        // TODO add your handling code here:
        Date d = this.tglAkhirPeminjaman;
        if (d == null) {
            d = new Date();
        }

        TimeChooser tc = new TimeChooser(d);
        if(tc.showEditTimeDlg(BookBorrowerGuiImpl.this) == TimeChooser.OK) {
            this.tglAkhirPeminjaman = tc.getDate();
            this.TextFieldTanggalAkhir.setText(this.tglAkhirPeminjaman.toString());
        }
    }//GEN-LAST:event_ButtonSetTanggalAkhirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookBorrowerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookBorrowerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookBorrowerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookBorrowerGuiImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookBorrowerGuiImpl().setVisible(true);
            }
        });
    }
    
    public void setAgent(BookBorrowerAgent a) {
        myAgent = a;
        setTitle(myAgent.getName());
    }
    
    @Override
    public void notifyUser(String message) {
        //
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKeluar;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSetTanggalAkhir;
    private javax.swing.JButton ButtonSetTanggalAwal;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JComboBox<String> ComboBoxNovelMajalah;
    private javax.swing.JLabel LabelAkhirPeminjaman;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelAwalPeminjaman;
    private javax.swing.JLabel LabelNamaPeminjam;
    private javax.swing.JLabel LabelNovelMajalah;
    private javax.swing.JTextArea TextAreaLogs;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldTanggalAkhir;
    private javax.swing.JTextField TextFieldTanggalAwal;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
